'use strict';
function operator(c,x,y,angle,step,team,firing,selected){
const stride=Math.sin(step)*5,accent=team===0?'#76edd9':'#ff9a80';
c.save();c.translate(x,y);c.fillStyle='#0007';c.beginPath();c.ellipse(2,4,20,16,0,0,Math.PI*2);c.fill();if(selected){c.strokeStyle='#9df5e0';c.lineWidth=2;c.strokeRect(-26,-26,52,52);}c.rotate(angle);
function part(x,y,w,h,color){c.fillStyle=color;c.fillRect(x,y,w,h);}
// Articulated boots and trouser legs.
part(-12,8+stride,9,15,'#59644e');part(3,8-stride,9,15,'#59644e');part(-13,18+stride,10,6,'#182325');part(3,18-stride,10,6,'#182325');
part(-13,-7,26,25,'#626f55');part(-11,-5,22,23,'#273a39');part(-14,3,5,12,'#708064');part(9,3,5,12,'#708064');
// Plate carrier, shoulder panels, magazine pouches, belt.
part(-8,-2,16,14,'#455447');part(-8,5,4,9,'#a0a083');part(-2,5,4,9,'#879477');part(4,5,4,9,'#9ba083');part(-11,17,22,4,'#151f22');part(-17,-6,6,14,'#758165');part(11,-6,6,14,'#758165');part(-18,-7,5,5,accent);part(13,-7,5,5,accent);
// Arms, gloves and carbine at the shoulder.
c.strokeStyle='#68765a';c.lineWidth=7;c.lineCap='round';c.beginPath();c.moveTo(-14,-4);c.lineTo(-12,-17);c.lineTo(0,-23);c.moveTo(14,-4);c.lineTo(13,-16);c.lineTo(5,-24);c.stroke();part(-2,-27,7,7,'#19272a');part(2,-35+(firing?2:0),5,27,'#101c21');part(0,-22,9,8,'#29383b');part(3,-42+(firing?2:0),3,9,'#11191e');part(1,-29,7,3,'#748078');
// Helmet, headset, night-vision mounting bracket.
c.fillStyle='#99a183';c.beginPath();c.ellipse(0,-10,10,11,0,0,Math.PI*2);c.fill();part(-11,-14,4,9,'#263c3e');part(7,-14,4,9,'#263c3e');part(-6,-18,12,4,'#56694f');part(-3,-22,6,5,'#26383b');part(-4,-6,8,3,accent);
if(firing){c.fillStyle='#ffdf83';c.beginPath();c.moveTo(4,-44);c.lineTo(-3,-51);c.lineTo(3,-49);c.lineTo(5,-59);c.lineTo(8,-49);c.lineTo(12,-52);c.lineTo(8,-43);c.fill();}c.restore();}
const canvas=document.getElementById('game'),c=canvas.getContext('2d'),$=id=>document.getElementById(id),B=Survival;
let s=B.create(),running=false,paused=false,lang='en',keys=new Set(),touch=null,previous=0,acc=0,scores=[],storageOK=true;
try{const data=JSON.parse(localStorage.getItem('breachline.survival.s2.scores')||'[]');if(Array.isArray(data))scores=data.filter(x=>Number.isFinite(x)&&x>=0).slice(0,5);}catch{storageOK=false;}
const words={en:{intro:'LAST STAND · One life. Survive the infected. WASD / arrows to move. On touch: drag anywhere on the arena. Your operator fires at the closest threat automatically.',start:'Start run',restart:'New run',pause:'Pause',resume:'Resume',ready:'Stay moving. New waves every 20 seconds.',dead:'Run ended. One life. No revive.',paused:'Paused — resume when ready.',local:'Local times only — editable, not a verified global ranking.',time:'Time',hp:'Health',wave:'Wave',kills:'Kills'},de:{intro:'LAST STAND · Ein Leben. Überlebe die Infizierten. WASD / Pfeiltasten: bewegen. Touch: im Spielfeld ziehen. Dein Operator feuert automatisch auf die nächste Bedrohung.',start:'Run starten',restart:'Neuer Run',pause:'Pause',resume:'Weiter',ready:'Bleib in Bewegung. Neue Wellen alle 20 Sekunden.',dead:'Run beendet. Ein Leben. Keine Wiederbelebung.',paused:'Pausiert — weiter, wenn du bereit bist.',local:'Nur lokale Zeiten — manipulierbar, keine verifizierte globale Rangliste.',time:'Zeit',hp:'Gesundheit',wave:'Welle',kills:'Abschüsse'}};
function ui(){const t=words[lang];$('upgrades').hidden=!s.upgrade;$('upgradeTitle').textContent=lang==='en'?'Field upgrade · time is paused':'Feldausrüstung · Zeit pausiert';$('damage').textContent=lang==='en'?'+50% base damage':'+50% Basisschaden';$('rate').textContent=lang==='en'?'15% shorter shot delay':'15% kürzere Schusspause';$('heal').textContent=lang==='en'?'Recover 40 health':'40 Gesundheit heilen';$('intro').textContent=t.intro;$('start').textContent=s.dead?t.restart:t.start;$('start').hidden=running;$('pause').hidden=!running;$('pause').textContent=paused?t.resume:t.pause;$('language').textContent=lang==='en'?'Deutsch':'English';$('status').textContent=s.dead?t.dead:paused?t.paused:t.ready;$('time').textContent=t.time+' '+s.time.toFixed(1)+'s';$('health').textContent=t.hp+' '+s.player.hp;$('wave').textContent=t.wave+' '+s.wave;$('kills').textContent=t.kills+' '+s.kills;$('scores').textContent=t.local+' '+scores.map(x=>x.toFixed(1)+'s').join(' · ')+(storageOK?'':' / Storage unavailable');}
function finish(){running=false;keys.clear();touch=null;scores.push(Math.round(s.time*10)/10);scores.sort((a,b)=>b-a);scores=scores.slice(0,5);try{localStorage.setItem('breachline.survival.s2.scores',JSON.stringify(scores));}catch{storageOK=false;}ui();}
function draw(){c.fillStyle='#1c322c';c.fillRect(0,0,960,640);c.fillStyle='#30413a';c.fillRect(0,260,960,120);c.fillRect(420,0,120,640);c.strokeStyle='#486052';c.lineWidth=2;for(let x=30;x<960;x+=60){c.beginPath();c.moveTo(x,0);c.lineTo(x,640);c.stroke();}for(let y=20;y<640;y+=60){c.beginPath();c.moveTo(0,y);c.lineTo(960,y);c.stroke();}
// Decorative park borders remain outside the playable movement area.
for(let x=50;x<960;x+=110){c.fillStyle='#12261e';c.beginPath();c.ellipse(x,5,28,17,0,0,7);c.fill();c.beginPath();c.ellipse(x,635,28,17,0,0,7);c.fill();}
for(const e of s.enemies){c.save();c.translate(e.x,e.y);c.rotate(e.angle+Math.PI/2);if(e.kind==='brute')c.scale(1.45,1.45);if(e.kind==='runner')c.scale(.8,1.15);c.fillStyle='#0006';c.beginPath();c.ellipse(2,4,14,10,0,0,7);c.fill();const gait=Math.sin(s.time*e.speed*.15+e.id)*4;c.fillStyle='#624d45';c.fillRect(-8,0,6,14+gait);c.fillRect(3,0,6,14-gait);c.fillStyle=e.kind==='runner'?'#d09a57':e.kind==='brute'?'#8d758c':'#829b68';c.fillRect(-11,-9,22,18);c.fillRect(-15,-20,6,19);c.fillRect(10,-20,6,19);c.fillStyle='#b4b887';c.beginPath();c.arc(0,-9,8,0,7);c.fill();c.fillStyle='#ff795d';c.fillRect(-5,-15,10,3);c.restore();}
c.save();c.translate(s.player.x,s.player.y);c.scale(.85,.85);if(s.player.inv>0)c.globalAlpha=.55+.45*Math.sin(s.time*40)**2;operator(c,0,0,s.player.angle+Math.PI/2,(keys.size||touch)?s.time*16:0,0,s.player.cool>.18,false);c.restore();
for(const b of s.shots){c.strokeStyle='#ffe7a0';c.lineWidth=3;c.beginPath();c.moveTo(b.x,b.y);c.lineTo(b.tx,b.ty);c.stroke();}
if(touch){c.strokeStyle='#83ebd5';c.lineWidth=3;c.beginPath();c.arc(touch.x,touch.y,48,0,7);c.stroke();c.beginPath();c.arc(touch.x+touch.dx*40,touch.y+touch.dy*40,15,0,7);c.stroke();}
if(s.dead||paused||s.upgrade||!running){c.fillStyle='#09151dbb';c.fillRect(0,0,960,640);c.textAlign='center';c.fillStyle='#e8efed';c.font='bold 40px system-ui';c.fillText(s.upgrade?(lang==='en'?'CHOOSE YOUR UPGRADE':'AUSRÜSTUNG WÄHLEN'):s.dead?(lang==='en'?'RUN ENDED':'RUN BEENDET'):paused?(lang==='en'?'PAUSED':'PAUSIERT'):'LAST STAND',480,290);c.font='24px system-ui';c.fillText(s.dead?s.time.toFixed(1)+' seconds':'BREACHLINE / SURVIVAL PROTOTYPE',480,335);}}
function frame(now){const dt=Math.min(.1,(now-previous)/1000||0);previous=now;if(running&&!paused){acc+=dt;while(acc>=1/60&&!s.dead){let x=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),y=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);if(touch){x=touch.dx;y=touch.dy;}B.step(s,{x,y},1/60);acc-=1/60;}if(s.dead)finish();}else acc=0;draw();ui();requestAnimationFrame(frame);}
$('start').onclick=()=>{s=B.create();running=true;paused=false;acc=0;keys.clear();touch=null;canvas.focus({preventScroll:true});};$('pause').onclick=()=>{paused=!paused;keys.clear();touch=null;if(!paused)canvas.focus({preventScroll:true});};$('language').onclick=()=>{lang=lang==='en'?'de':'en';document.documentElement.lang=lang;ui();};
window.addEventListener('keydown',e=>{if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){if(e.target.tagName==='BUTTON')return;e.preventDefault();keys.add(e.key);}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{keys.clear();touch=null;if(running)paused=true;});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){paused=true;keys.clear();touch=null;}});
function position(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*960/r.width,y:(e.clientY-r.top)*640/r.height};}
canvas.addEventListener('pointerdown',e=>{if(!running||paused||touch)return;canvas.setPointerCapture(e.pointerId);const p=position(e);touch={...p,dx:0,dy:0,id:e.pointerId};});canvas.addEventListener('pointermove',e=>{if(!touch||touch.id!==e.pointerId)return;const p=position(e),x=p.x-touch.x,y=p.y-touch.y,d=Math.max(40,Math.hypot(x,y));touch.dx=x/d;touch.dy=y/d;});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(touch?.id===e.pointerId)touch=null;});
ui();requestAnimationFrame(frame);

for(const choice of ['damage','rate','heal'])$(choice).onclick=()=>{if(B.choose(s,choice)){keys.clear();touch=null;acc=0;canvas.focus({preventScroll:true});ui();}};